/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.kredit;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Sigma
 */
public class CRUD_Kredit_New extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_Kredit_New
     */
    
    public CRUD_Kredit_New() {
        initComponents();
        kodeKontrakOtomatis();
        customerList();
        assetList();
    }
    
    public LocalDate dateNow() {
        LocalDate date_now = LocalDate.now();
        return date_now;
    }
    
    public void kodeKontrakOtomatis(){
        try {
            String sql = "SELECT * FROM kredit order by no_kontrak desc";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            if (res.next()) {
                String kode = res.getString("no_kontrak").substring(4);
                String AN = "" + (Integer.parseInt(kode) +1 );
                String Nol = "";
                
                if (AN.length() == 1) {
                    Nol= "00";
                } else if (AN.length() == 2) {
                    Nol = "0";
                } else if (AN.length() == 3) {
                    Nol = "";
                }
                
                input_no_kontrak.setText("CODE" + Nol + AN);
                input_no_kontrak.setEnabled(false);
            } else {
                input_no_kontrak.setText("CODE001");
                input_no_kontrak.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void customerList () {
        try {
            String sql = "SELECT * FROM customer";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while (res.next()) {                
                String nik = res.getString("nik");
                input_nik_customer.addItem(nik);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void assetList (){
        try {
            String sql = "SELECT * FROM barang";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while (res.next()) {                
                String id_barang = res.getString("id_barang");
                input_id_asset.addItem(id_barang);
            }
        } catch (Exception e) {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        input_nik_customer = new javax.swing.JComboBox<>();
        input_no_kontrak = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        input_id_asset = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        input_harga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        input_tenor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        input_jumlah = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        btn_homepage = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        input_nama_customer = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        input_nama_barang = new javax.swing.JTextField();
        btn_hitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORM KREDIT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel2.setText("NO KONTRAK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        input_nik_customer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- select nik --" }));
        input_nik_customer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                input_nik_customerItemStateChanged(evt);
            }
        });
        input_nik_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                input_nik_customerMouseClicked(evt);
            }
        });
        input_nik_customer.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                input_nik_customerInputMethodTextChanged(evt);
            }
        });
        input_nik_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nik_customerActionPerformed(evt);
            }
        });
        input_nik_customer.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                input_nik_customerPropertyChange(evt);
            }
        });
        jPanel1.add(input_nik_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 270, -1));

        input_no_kontrak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_no_kontrakActionPerformed(evt);
            }
        });
        jPanel1.add(input_no_kontrak, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 270, -1));

        jLabel3.setText("NIK CUSTOMER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        jLabel4.setText("ASSET (BARANG)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 40));

        input_id_asset.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- select id asset --" }));
        input_id_asset.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                input_id_assetItemStateChanged(evt);
            }
        });
        jPanel1.add(input_id_asset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 270, -1));

        jLabel5.setText("HARGA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 140, 30));

        input_harga.setEnabled(false);
        input_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_hargaActionPerformed(evt);
            }
        });
        jPanel1.add(input_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 270, -1));

        jLabel6.setText("TENOR (bulan)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 40));

        input_tenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_tenorActionPerformed(evt);
            }
        });
        input_tenor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                input_tenorPropertyChange(evt);
            }
        });
        jPanel1.add(input_tenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 270, -1));

        jLabel7.setText("JUMLAH YANG HARUS DIBAYAR");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 30));

        input_jumlah.setEnabled(false);
        jPanel1.add(input_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 270, -1));

        btn_submit.setText("Submit");
        btn_submit.setEnabled(false);
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 90, -1));

        btn_homepage.setText("Back Homepage");
        btn_homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homepageActionPerformed(evt);
            }
        });
        jPanel1.add(btn_homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        jLabel8.setText("Nama Customer");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

        input_nama_customer.setEnabled(false);
        jPanel1.add(input_nama_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 270, -1));

        jLabel9.setText("Nama Barang");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        input_nama_barang.setEnabled(false);
        input_nama_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nama_barangActionPerformed(evt);
            }
        });
        jPanel1.add(input_nama_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 270, -1));

        btn_hitung.setText("Hitung");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_no_kontrakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_no_kontrakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_no_kontrakActionPerformed

    private void input_nik_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nik_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nik_customerActionPerformed

    private void input_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_hargaActionPerformed

    private void input_tenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_tenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_tenorActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO kredit (`no_kontrak`, `customer`, `asset`, `harga`, `tenor`, `jumlah`,`tanggal_kredit`) VALUES ('"+input_no_kontrak.getText()+"','"+input_nik_customer.getSelectedItem()+"','"+input_id_asset.getSelectedItem()+"','"+input_harga.getText()+"','"+input_tenor.getText()+"','"+input_jumlah.getText()+"','"+dateNow()+"')";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            Homepage homepage = new Homepage();
            homepage.show();
            dispose();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void input_nik_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_nik_customerMouseClicked
        // TODO add your handling code here:
//        System.out.println("Show");
//        System.out.println(input_nik_customer.getSelectedItem());
    }//GEN-LAST:event_input_nik_customerMouseClicked

    private void input_nik_customerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_input_nik_customerItemStateChanged
//        System.out.println(input_nik_customer.getSelectedIndex());
        System.out.println(input_nik_customer.getSelectedItem());
        try {
            String sql = "SELECT * FROM customer where `nik` = '"+input_nik_customer.getSelectedItem()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while (res.next()) {                
                String nama = res.getString("nama");
                input_nama_customer.setText(nama);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_input_nik_customerItemStateChanged

    private void input_nik_customerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_input_nik_customerPropertyChange
        // TODO add your handling code here:
//        System.out.println("Show");
    }//GEN-LAST:event_input_nik_customerPropertyChange

    private void btn_homepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homepageActionPerformed
        // TODO add your handling code here:
        Homepage homepage = new Homepage();
        homepage.show();
        
        dispose();
    }//GEN-LAST:event_btn_homepageActionPerformed

    private void input_id_assetItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_input_id_assetItemStateChanged
        // TODO add your handling code here:
        System.out.println(input_id_asset.getSelectedItem());
        try {
            String sql = "SELECT * FROM barang where `id_barang` = '"+input_id_asset.getSelectedItem()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while (res.next()) {                
                String nama_barang = res.getString("nama_barang");
                String harga = res.getString("harga");
                input_nama_barang.setText(nama_barang);
                input_harga.setText(harga);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_input_id_assetItemStateChanged

    private void input_nama_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nama_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nama_barangActionPerformed

    private void input_nik_customerInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_input_nik_customerInputMethodTextChanged
        // TODO add your handling code here:
//        System.out.println(input_nik_customer.getSelectedItem());
    }//GEN-LAST:event_input_nik_customerInputMethodTextChanged

    private void input_tenorPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_input_tenorPropertyChange
//        System.out.println(input_tenor.getText());
    }//GEN-LAST:event_input_tenorPropertyChange

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        String harga = input_harga.getText();
        String tenor = input_tenor.getText();
        Integer jumlah = Integer.parseInt(harga)+(Integer.parseInt(harga)/100)*10;
        Integer result = jumlah/Integer.parseInt(tenor);
        System.out.println(jumlah);
        System.out.println(result);
        btn_submit.setEnabled(true);
        input_jumlah.setText(result.toString());
    }//GEN-LAST:event_btn_hitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_Kredit_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_Kredit_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_Kredit_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_Kredit_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_Kredit_New().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_homepage;
    private javax.swing.JButton btn_submit;
    private javax.swing.JTextField input_harga;
    private javax.swing.JComboBox<String> input_id_asset;
    private javax.swing.JTextField input_jumlah;
    private javax.swing.JTextField input_nama_barang;
    private javax.swing.JTextField input_nama_customer;
    private javax.swing.JComboBox<String> input_nik_customer;
    private javax.swing.JTextField input_no_kontrak;
    private javax.swing.JTextField input_tenor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
