/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.kredit;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sigma
 */
public final class CRUD_payment extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_payment
     */
    private static String defaultDatePattern = "yyyy-MM-dd";
    public static SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
    private static Integer idPembayaran = 0;
    
    public CRUD_payment() throws ParseException {
        initComponents();
        kontrak();
        payment();
        show_data();
    }
    
    public static final String addMonth(String strDate, int months) {
        Date date;
        try {
            date = dateFormatter.parse(strDate);
        } catch (ParseException e) {
            return null;
        }
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        cal.add(Calendar.MONTH, months);
        return dateFormatterByPattern(cal.getTime(), "yyyy-MM-dd");
    }
    
    public static String dateFormatterByPattern(Date date, String pattern) {
        SimpleDateFormat sdf = new SimpleDateFormat(pattern);
        if (date != null) {
            return sdf.format(date);
        } else {
            return sdf.format(new Date());
        }
    }
    
    public Object[] dateCompare (String tanggal_kredit , int angsuran) {
        String tanggal = "";
        String jatuhTempo = "";
        String[] tanggal_jatuh_tempo;
        try {
            LocalDate date_now = LocalDate.now();
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd",Locale.ENGLISH);
            Date startDate = simpleDateFormat.parse(tanggal_kredit);
            String add = addMonth(tanggal_kredit,angsuran);
            Date addMonths = simpleDateFormat.parse(add); // 2022-07-22
            Date endDate = simpleDateFormat.parse(date_now.toString()); // 2022-07-25
            long difference = 0;
            int daysBetween = 0;
            if (addMonths.getTime() < endDate.getTime()) {
                difference = endDate.getTime() - addMonths.getTime();
                daysBetween = (int) (difference / (1000*60*60*24));
            } else {
                difference = 0;
                daysBetween = 0;
            }
            jatuhTempo = add;
            tanggal = String.valueOf(daysBetween);
        } catch (Exception e) {
        }
        return new Object[]{tanggal,jatuhTempo};
    }
    
    public void payment() {
        try {
            String sql = "SELECT * FROM kredit WHERE no_kontrak = 'CODE001'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while (res.next()) {                
                String no_kontrak = res.getString("no_kontrak");
                String jumlah = res.getString("jumlah");
            }
        } catch (Exception e) {
        }
    }
    
    public void kontrak () {
        try {
            String sql = "SELECT * FROM kredit";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while (res.next()) {                
                String no_kontrak = res.getString("no_kontrak");
                input_no_kontrak.addItem(no_kontrak);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public static final int angsuranKe(String no_kontrak) {
        int angsuranText = 0;
        try {
            String sql = "SELECT * FROM pembayaran WHERE no_kontrak = '"+no_kontrak+"' ORDER BY angsuran";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while (res.next()) {                
                String angsuran = res.getString("angsuran");
                angsuranText = Integer.parseInt(angsuran);
            }
        } catch (Exception e) {
        }
        return angsuranText;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        input_angsuran = new javax.swing.JTextField();
        input_bayar = new javax.swing.JTextField();
        input_jatuh_tempo = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pembayaran = new javax.swing.JTable();
        btn_homepage = new javax.swing.JButton();
        input_no_kontrak = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        input_denda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        input_pembayaran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        input_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        input_id_pembayaran = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tanggal_jatuh_tempo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORM PEMBAYARAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel2.setText("No Kontrak");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        jLabel3.setText("Angsuran Ke ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        jLabel4.setText("Jumlah yang harus dibayar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 210, 30));

        jLabel5.setText("Total Hari Jatuh Tempo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 30));

        input_angsuran.setEnabled(false);
        jPanel1.add(input_angsuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 230, -1));

        input_bayar.setEnabled(false);
        jPanel1.add(input_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 230, -1));

        input_jatuh_tempo.setEnabled(false);
        jPanel1.add(input_jatuh_tempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 230, -1));

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        table_pembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "No Kontrak", "Angsuran Ke", "Jml Angsuran", "Denda", "Pembayaran"
            }
        ));
        table_pembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_pembayaran);
        if (table_pembayaran.getColumnModel().getColumnCount() > 0) {
            table_pembayaran.getColumnModel().getColumn(0).setMaxWidth(15);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 490, 160));

        btn_homepage.setText("Back Homepage");
        btn_homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homepageActionPerformed(evt);
            }
        });
        jPanel1.add(btn_homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        input_no_kontrak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- select no kontrak --" }));
        input_no_kontrak.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                input_no_kontrakItemStateChanged(evt);
            }
        });
        input_no_kontrak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_no_kontrakActionPerformed(evt);
            }
        });
        jPanel1.add(input_no_kontrak, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 230, -1));

        jLabel6.setText("Total Denda");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 30));

        input_denda.setEnabled(false);
        jPanel1.add(input_denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 230, -1));

        jLabel7.setText("Total Pembayaran");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 30));

        input_pembayaran.setEnabled(false);
        jPanel1.add(input_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 230, -1));

        jLabel8.setText("Nama Customer");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        input_name.setEnabled(false);
        jPanel1.add(input_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 230, -1));

        jLabel9.setText("Id Pembayaran");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        input_id_pembayaran.setEnabled(false);
        jPanel1.add(input_id_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 230, -1));

        jLabel10.setText("Tanggal Jatuh Tempo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        tanggal_jatuh_tempo.setEnabled(false);
        jPanel1.add(tanggal_jatuh_tempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homepageActionPerformed
        // TODO add your handling code here:
        Homepage homepage = new Homepage();
        homepage.show();
        
        dispose();
    }//GEN-LAST:event_btn_homepageActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO pembayaran (`no_kontrak`, `angsuran`, `jumlah`, `denda`, `total`) VALUES ('"+input_no_kontrak.getSelectedItem()+"','"+input_angsuran.getText()+"','"+input_bayar.getText()+"','"+input_denda.getText()+"','"+input_pembayaran.getText()+"')";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        show_data();
        form_kosong();
    }//GEN-LAST:event_btn_submitActionPerformed

    private void input_no_kontrakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_no_kontrakActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_input_no_kontrakActionPerformed

    private void input_no_kontrakItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_input_no_kontrakItemStateChanged
        // TODO add your handling code here:
        try {
            String sql = "SELECT kredit.no_kontrak, customer.nama, kredit.jumlah, kredit.harga, kredit.tenor, kredit.tanggal_kredit FROM kredit INNER JOIN customer ON kredit.customer=customer.nik WHERE no_kontrak = '"+input_no_kontrak.getSelectedItem()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while (res.next()) {                
                
                String jumlah = res.getString("jumlah");
                String harga = res.getString("harga");
                String no_kontrak = res.getString("no_kontrak");
                String nama = res.getString("nama");
                String tanggal_kredit = res.getString("tanggal_kredit");
                Object[] date = dateCompare(tanggal_kredit,angsuranKe(no_kontrak));
                int a = angsuranKe(no_kontrak)+1;
              
                int total_denda = 1000*Integer.parseInt((String) date[0]);
                int total_pembayaran = Integer.parseInt(jumlah)+total_denda;
                
                input_name.setText(nama);
                input_bayar.setText(jumlah);
                input_angsuran.setText(String.valueOf(a));
                input_jatuh_tempo.setText((String) date[0]);
                tanggal_jatuh_tempo.setText((String) date[1]);
                input_denda.setText(String.valueOf(total_denda));
                input_pembayaran.setText(String.valueOf(total_pembayaran));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_input_no_kontrakItemStateChanged

    private void table_pembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pembayaranMouseClicked
        // TODO add your handling code here:
        int baris = table_pembayaran.rowAtPoint(evt.getPoint());
        String id = table_pembayaran.getValueAt(baris, 0).toString();
        input_id_pembayaran.setText(id);
        String no_kontrak = table_pembayaran.getValueAt(baris, 1).toString();
        input_no_kontrak.setSelectedItem(no_kontrak);
        String angsuran = table_pembayaran.getValueAt(baris, 2).toString();
        input_angsuran.setText(angsuran);
        String jumlah_bayar = table_pembayaran.getValueAt(baris, 3).toString();
        input_bayar.setText(jumlah_bayar);
        String denda = table_pembayaran.getValueAt(baris, 4).toString();
        input_denda.setText(denda);
        String pembayaran = table_pembayaran.getValueAt(baris, 5).toString();
        input_pembayaran.setText(pembayaran);
        input_angsuran.setEnabled(true);
        input_bayar.setEnabled(true);
        input_jatuh_tempo.setEnabled(true);
        input_denda.setEnabled(true);
        input_pembayaran.setEnabled(true);
    }//GEN-LAST:event_table_pembayaranMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="UPDATE pembayaran SET no_kontak = '"+input_no_kontrak.getSelectedItem()+"', angsuran = '"+input_angsuran.getText()+"', jumlah = '"+input_bayar.getText()+"', denda = '"+input_denda.getText()+"', total = '"+input_pembayaran.getText()+"' WHERE NIK = '"+input_id_pembayaran.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        input_angsuran.setEnabled(false);
        input_bayar.setEnabled(false);
        input_jatuh_tempo.setEnabled(false);
        input_denda.setEnabled(false);
        input_pembayaran.setEnabled(false);
    }//GEN-LAST:event_btn_editActionPerformed

    private void show_data(){
//         membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("No Kontrak");
        model.addColumn("Angsuran");
        model.addColumn("Jml Angsuran");
        model.addColumn("Denda");
        model.addColumn("Pembayaran");
        
        //menampilkan data database kedalam tabel
        try {
            String sql = "SELECT pembayaran.id_pembayaran, pembayaran.no_kontrak, pembayaran.angsuran, pembayaran.jumlah, pembayaran.denda, pembayaran.total FROM pembayaran";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString("id_pembayaran"),res.getString("no_kontrak"),res.getString("angsuran"),res.getString("jumlah"),res.getString("denda"),res.getString("total")});
            }
            table_pembayaran.setModel(model);
            System.out.print("Berhasil Nampil Data");
        } catch (SQLException e) {
            System.out.print("Gagal Nampil Data");
        }
    }
    
    private void form_kosong() {
        input_id_pembayaran.setText(null);
        input_no_kontrak.setSelectedItem("-- select no kontrak --");
        input_name.setText(null);
        input_angsuran.setText(null);
        input_bayar.setText(null);
        input_jatuh_tempo.setText(null);
        input_denda.setText(null);
        input_pembayaran.setText(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CRUD_payment().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(CRUD_payment.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_homepage;
    private javax.swing.JButton btn_submit;
    private javax.swing.JTextField input_angsuran;
    private javax.swing.JTextField input_bayar;
    private javax.swing.JTextField input_denda;
    private javax.swing.JTextField input_id_pembayaran;
    private javax.swing.JTextField input_jatuh_tempo;
    private javax.swing.JTextField input_name;
    private javax.swing.JComboBox<String> input_no_kontrak;
    private javax.swing.JTextField input_pembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_pembayaran;
    private javax.swing.JTextField tanggal_jatuh_tempo;
    // End of variables declaration//GEN-END:variables
}
