/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.kredit;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sigma
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_data_karyawan = new javax.swing.JButton();
        btn_data_customer = new javax.swing.JButton();
        btn_data_kredit = new javax.swing.JButton();
        btn_data_pembayaran = new javax.swing.JButton();
        btn_data_asset = new javax.swing.JButton();
        btn_report = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sigma\\Documents\\belajar\\logo.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("WELCOME PT. BUSSAN AUTO FINANCE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel3.setText("Sistem Informasi Pendataan Data Leasing");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        btn_data_karyawan.setText("Data Karyawan");
        btn_data_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_data_karyawanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_data_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 140, -1));

        btn_data_customer.setText("Data Customer");
        btn_data_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_data_customerActionPerformed(evt);
            }
        });
        jPanel1.add(btn_data_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 140, -1));

        btn_data_kredit.setText("Data Kredit");
        btn_data_kredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_data_kreditActionPerformed(evt);
            }
        });
        jPanel1.add(btn_data_kredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 140, -1));

        btn_data_pembayaran.setText("Data Pembayaran");
        btn_data_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_data_pembayaranActionPerformed(evt);
            }
        });
        jPanel1.add(btn_data_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 160, -1));

        btn_data_asset.setText("Data Aset");
        btn_data_asset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_data_assetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_data_asset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 160, -1));

        btn_report.setText("Report");
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });
        jPanel1.add(btn_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 160, -1));

        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_data_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_data_pembayaranActionPerformed
        // TODO add your handling code here:
        CRUD_payment pembayaran;
        try {
            pembayaran = new CRUD_payment();
            pembayaran.show();
        } catch (ParseException ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dispose();
    }//GEN-LAST:event_btn_data_pembayaranActionPerformed

    private void btn_data_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_data_karyawanActionPerformed
        // TODO add your handling code here:
        CRUD_karyawan karyawan = new CRUD_karyawan();
        karyawan.show();
        
        dispose();
    }//GEN-LAST:event_btn_data_karyawanActionPerformed

    private void btn_data_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_data_customerActionPerformed
        // TODO add your handling code here:
        CRUD_customer customer = new CRUD_customer();
        customer.show();
        
        dispose();
    }//GEN-LAST:event_btn_data_customerActionPerformed

    private void btn_data_kreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_data_kreditActionPerformed
        // TODO add your handling code here:
        CRUD_Kredit_New kredit = new CRUD_Kredit_New();
        kredit.show();
        
        dispose();
    }//GEN-LAST:event_btn_data_kreditActionPerformed

    private void btn_data_assetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_data_assetActionPerformed
        // TODO add your handling code here:
        CRUD_barang barang = new CRUD_barang();
        barang.show();
        
        dispose();
    }//GEN-LAST:event_btn_data_assetActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
        // TODO add your handling code here:
        RepotPage repot = new RepotPage();
        repot.show();
        
        dispose();
    }//GEN-LAST:event_btn_reportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_data_asset;
    private javax.swing.JButton btn_data_customer;
    private javax.swing.JButton btn_data_karyawan;
    private javax.swing.JButton btn_data_kredit;
    private javax.swing.JButton btn_data_pembayaran;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
